### ISSUE TITLE
Support different validation norms for different variables

### ISSUE THREAD

**Issue by matthewhoffman** [MPAS-Dev/compass#135]
The `compare_variables` method in the `validate.py` package supports optional nonzero values of l1, l2, and linf norms.  However, if nonzero norm values are required, they are unlikely to be the same for each variable being compared.  The old compass system let each variable have its own norms defined, e.g.:
`<field name="normalVelocity" l2_norm="1.0e-13"/>`

I can imagine two ways to accomplish this:
1. simply call `compare_variables` multiple times, once with each norm value required.
2. modify the function to support some sort of data structure that provides per-variable norm values.

I think 1. is sufficient (and certainly easier to implement).  But I wanted to open an issue to see if there are other thoughts.

A related item is that the old system allowed a subset of the l1, l2, and linf norms to be checked for a given variable, but the new system seems to only check all 3 norms.  That's less flexible, but I think that's an ok restriction.

**Comment by matthewhoffman** [comment]
It looks like the validation package already is smart enough to not clobber the result of a previous call, meaning option 1 should work correctly:
https://github.com/MPAS-Dev/compass/blob/master/compass/validate.py#L70-L71
Nice!

**Comment by matthewhoffman** [comment]
A related issue is it would be nice if the stdout stated what norm was being used for each comparison (or at least of the norm tolerance was nonzero).

**Comment by xylar** [comment]
@matthewhoffman, I am up for implementing (or helping to implement) whatever would be helpful for you.  I think you should design this functionality since the ocean test cases have only ever used zero as the (rather redundant) tolerances.  We just don't have any examples to work from to figure out how to make this functionality useful.  That being said, going through your points, I think all the functionality you need may already be in place, and the main thing that may be needed is improvements in documentation (which I'm also happy to help with).

> I think 1. is sufficient (and certainly easier to implement). But I wanted to open an issue to see if there are other thoughts.

I think 1 is easier but it won't be very compact.  I can't think of a very elegant way to implement 2, though.  You could have a list of dictionaries, each with a list of variables and the tolerances as entries.  But that starts to look an awful lot like a complicated way of doing 1 that won't be any easier to read.

> It looks like the validation package already is smart enough to not clobber the result of a previous call, meaning option 1 should work correctly

Yeah, we have some test cases that check different output files and variables already, so this was already needed.

> A related item is that the old system allowed a subset of the l1, l2, and linf norms to be checked for a given variable, but the new system seems to only check all 3 norms. That's less flexible, but I think that's an ok restriction.

Looking at the code, if you pass `None` for any norm, it shouldn't be used.  But this needs to be tested and added to the docstring and documentation. 

> A related issue is it would be nice if the stdout stated what norm was being used for each comparison (or at least of the norm tolerance was nonzero).

I think you need to set `quiet=False` and you should get the output you're after.   If that doesn't work for you, let me know.

**Comment by matthewhoffman** [comment]
You probably saw how I ended up implementing 1 in my current landice branch after realizing I could call the validation multiple times in a row.  I was satisfied with this solution.  Thanks for pointing out the ability to pass `None` to a norm and how to make use of the `quiet` option.  I probably could have picked up on those details myself but I hadn't - I think over time I will notice more of the nuances with the code.  I can make a docs PR to include those details.

**Comment by xylar** [comment]
Thanks so much for making that PR!
