### ISSUE TITLE
Consider using 1 PIO task per core

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/compass#281]
All test cases that currently run an MPAS model first set `config_pio_num_iotasks` and `config_pio_stride` so that there is one PIO task per node.

I can't find the discussion but I believe we had done some PIO1 and PIO2 benchmarking in the past and had discovered that, while PIO1 performed much better with these settings, PIO2 did fine with one PIO task per CPU (the MPAS default).  @mark-petersen, do you recall this discussion and the benchmarking?  I believe you may have been the one who did the work.

It would be nice to leave the defaults:
```
    config_pio_num_iotasks = 0
    config_pio_stride = 1
```
This would allow a user to override these namelist options without `compass` then reverting back to its own chosen values when you do `compass run`.

**Comment by xylar** [comment]
@matthewhoffman, do you have experience related to this issue that you want to share?  I believe you're using PIO1 for your Albany configurations right now so maybe this needs to wait until you're using SCORPIO for those setups.

**Comment by matthewhoffman** [comment]
@xylar , I don't have much to add.  My experience with PIO1 was what you say in the issue - that you get bad performance with 1 PIO per task per processor and things work much better with 1 or2 per *node* instead.  But I never did a careful analysis.  I have not revisited the issues with PIO2, so that's great if that issue has largely gone away.

We are still using PIO1 on Badger, but we have switched to PIO2 on Cori.  Once we rebuild the Badger software stack with spack (hopefully in the coming months as you know), we'll switch over to PIO2 there too.  So I think we don't need to let the Badger situation influence the decision here.

**Comment by mark-petersen** [comment]
I agree that
```
    config_pio_num_iotasks = 0
    config_pio_stride = 1
```
is the best default. Otherwise we waste more time adjusting for different node counts, especially if you use an interactive log-in and don't match the iotasks*stride by mistake.

I didn't realize that this is actually the best setting for PIO2. I had not done that testing. @philipwjones are you aware of PIO2 testing with a recommended best stride length?

But if that is the best PIO2 setting, then all the more reason to make this the default setting. Thanks, @xylar.

**Comment by xylar** [comment]
It may also have been Phil Wolfram that did the benchmarking I'm thinking of.

**Comment by philipwjones** [comment]
There has been some testing recently by Jayesh's group - I asked about it during our perf group meeting today and will have Jayesh comment on this (looks like I can't tag him in this space).  Generically speaking, using 1 I/O task per node (rather than per MPI task) is still the most appropriate default I think.

**Comment by xylar** [comment]
Thanks @philipwjones.  The only circumstance under which I'm aware of this having caused trouble was when someone (@hollyhan) wanted to run on a single CPU instead of 4 CPUs.  It just meant she had to manually switch back to the MPAS default to make that work and then to run with `mpirun` instead of `compass run`.  That's an unusual enough case that I think we can stick with the existing behavior.

I will close this for now but would still appreciate any comments from @jayeshkrishna or anyone else from the SCORPIO team.

**Comment by dqwu** [comment]
PIO1 (SCORPIO classic) is deprecated for E3SM.
For PIO2 (SCORPIO), you can test with different strides (1 or number of cores per compute node) for compasison.
To view IO performance, you can look at the IO stats summary info in spio_stats.***.tar.gz in the run directory.

**Comment by dqwu** [comment]
@xylar What configs are you concerned about? If you have a benchmark perf test for MPAS on Cori or Summit,
we can run it with various strides for testing MPAS performance.

**Comment by xylar** [comment]
@dqwu, I think what we're mostly wanting is a rule of thumb.  Is it better for `compass` to configure MPAS standalone runs to have one PIO2 task per CPU or one task per node?  I'm not sure it's worth the trouble of doing testing on any particular machine for this purpose.  We currently do one PIO2 task per node and if this isn't a bad way to go, I don't think we want to change it.  If your intuition would be that we should do something else, maybe it would be worth more testing.
