### ISSUE TITLE
Build MPAS standalone from `compass` command line

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/compass#289]
It would be nice to either have a tool (e.g. `compass build`) or a set of flags for `compass setup` and `compass suite` that let a user build MPAS components in a more automated way.

Currently, users need to look up the argument to `make` for a given machine, compiler and MPI combination:
https://mpas-dev.github.io/compass/latest/developers_guide/machines/index.html#supported-machines
That would be easy to automate, sparing users from needing to look this up or know it.

It would be important to support additional make options like `DEBUG=true` and to indicate if `make clean` is needed.

**Comment by xylar** [comment]
@mark-petersen and @matthewhoffman, do you have thoughts on this?

**Comment by mark-petersen** [comment]
Yes, I think this could be helpful to streamline the process. I'm sure we could still type the make file ourselves by hand. I think that is helpful when teaching people, so there are fewer layers of scripts to understand. It would also be nice to have a --dryrun option (or similar) that tells you what the make command is without actually running it.

**Comment by matthewhoffman** [comment]
I can see the appeal, but I also worry about having to build and maintain one more layer.  I think it might create as much complexity as it solves.  I'm thinking this because I immediately think about the `ALBANY=true` flag we typically use, but then if Albany isn't compiled on a machine we don't use it.  So I worry this new command would end up supporting all the make options for MPAS, at which point all it would be doing is choosing the correct default build target for the current machine.  The documentation is very thorough, so I think asking users to refer to that is reasonable.  Have there been use cases where that seems insufficient?

**Comment by xylar** [comment]
Okay, I'll leave this on the back burner.

> Have there been use cases where that seems insufficient?

It just seems dumb to me to have documentation of a table of make targets for a given system that could easily just be known by compass instead of looked up by the user.

But I get what both of you are saying about the complexity of maintaining another layer of automation.
