### ISSUE TITLE
Add fuctionality for dealing with a matrix of builds

### ISSUE THREAD

**Issue by sbrus89** [MPAS-Dev/compass#346]
For testing purposes, it would be convenient to have the ability to run a test suite with multiple different MPAS builds (i.e., intel/gnu, debug/optimized, openmp/no openmp). 

This would require compass to be able to automate the build procedure and rename the executables for each build configuration. It would also need compass run to handle loading the appropriate environments and linking the corresponding executables.

**Comment by sbrus89** [comment]
We should also get @mark-petersen's thoughts on this since I know he tests with multiple builds very frequently.

**Comment by sbrus89** [comment]
@xylar, I see. It makes sense why this is tricky from within compass. I'm wondering if we could have a driver script to implement this functionality that would live outside the conda package? I realize that's kind of antithetical to the philosophy of compass, but reminds me of other discussions we've had around implementing a bisect capability.

**Comment by xylar** [comment]
@sbrus89, I thought about that, too.  We can explore that further.  It would seemingly need to take a config file similar to my prototype for the `git bisect` script.  The config file would provide things like the matrix of configurations to build (compiler, mpi, debug or optimized, openmp or not); the directory where MPAS will be built, the base work directory, the `compass setup` or `compass suite` command (minus the `-p` and `-w` flags) 

Presumably, there would be a setup driver and a run driver (which would be simlinked in to the base work directory along with the config file).

I can start working on a prototype as I have time.

**Comment by mark-petersen** [comment]
I build executables at the command line outside of compass, and then set up different case directories for different compilers by hand. That is certainly a manual part of the process, and an easy place to mix up the match of executables and directories. But to automate with several compilers, compass would need to "encompass" the build and corresponding case directories. Would that be better served by a user-generated bash script for simplicity?

Another consideration is that I keep numerous E3SM worktree directories outside of my compass directories, and just point to the executable directory each time I use `compass suite` and `compass setup`, rather than the E3SM submodule inside of compass.

**Comment by xylar** [comment]
> Would that be better served by a user-generated bash script for simplicity?

@mark-petersen, I really don't think so.  I think it would be easy to have config options or something like that to support any custom build options.  There's nothing stopping developers from having their won scripts but it would be much nicer if we didn't have to maintain separate scripts for each machine since compass is perfectly capable knowing how to do this in each machine.

> Another consideration is that I keep numerous E3SM worktree directories outside of my compass directories, and just point to the executable directory each time I use `compass suite` and `compass setup`, rather than the E3SM submodule inside of compass.

Yes, of course.  The path to the MPAS model would be a config option and command-line argument just like it is for `compass setup` and `compass suite`.

**Comment by xylar** [comment]
> Would that be better served by a user-generated bash script for simplicity?

@mark-petersen, I also think it's not a good use of everyone's time to make their own bash scripts for this if there is a common set of functionality that many of us want.

**Comment by xylar** [comment]
I have tested a solution to this in https://github.com/xylar/compass/tree/add_matrix_build.  It relies on functionality from https://github.com/MPAS-Dev/MPAS-Tools/pull/460, so I will wait until after I have released a new version of MPAS-Tools and updated compass to use it before I bring in that functionality.

**Comment by xylar** [comment]
Closed via https://github.com/MPAS-Dev/compass/pull/373
