### ISSUE TITLE
Default executable location uses a relative path

### ISSUE THREAD

**Issue by matthewhoffman** [MPAS-Dev/compass#361]
The default executable location appears to be using a relative path, such that if you execute `compass suite` or `compass setup` from a directory location other than the root of the compass installation, an error occurs if you have not specified the executable location with `-p`.  For example I find I often run `compass suite` from the build directory inside the MALI submodule.  If from that location I run:
`compass suite -c landice -t full_integration -s -b /lustre/scratch4/turquoise/mhoffman/COMPASS_REGRESSION/BASELINE -w /lustre/scratch4/turquoise/mhoffman/COMPASS_REGRESSION/testing`
I get this error:
```
FileNotFoundError: [Errno 2] No such file or directory: '/turquoise/usr/projects/climate/mhoffman/compass/compass/MALI-Dev/components/mpas-albany-landice/MALI-Dev/components/mpas-albany-landice'
```

I would prefer that the behavior when `-p` is not included would be to always look for the default submodule location relative to the root of the COMPASS install rather than the current location.  I don't see a downside to that change, but there could be some other use case I haven't thought of.

**Comment by xylar** [comment]
@matthewhoffman, this is the intended behavior.  I will have to think about whether there is an easy way around this.

**Comment by xylar** [comment]
Currently, there is not an environment variable (or config option) that defines the root of the compass  branch.  I but one could be added and then used to modify the MPAS model path.  It's not a trivial change, though.

**Comment by matthewhoffman** [comment]
Thanks, @xylar .  If there is not a simple fix, then it's not worth worrying about.  It's a minor inconvenience.  Feel free to close this issue if you think we can consider it resolved.

**Comment by xylar** [comment]
It's turning out to be more complicated than I hoped.  The config parser works hard to make relative paths into absolute paths relative to the current working directory.  That behavior is somewhat problematic anyway if the config parser moves over to MPAS-Tools (as I hope it will).

In general, I think it is still best to assume relative paths are relative to the current directory, not the root of the compass branch.  But config options that aren't supplied by a user (like the `mpas_model` relative path) should use the compass branch rather than the current directory.

**Comment by matthewhoffman** [comment]
I'm happy to leave this as is for now - it's not a very big inconvenience.
