### ISSUE TITLE
Sea ice ~70 m thick in 2 spots in v2.LR.historical_0101 run

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/compass#444]
We likely need to revisit how we cull cells for sea ice in any future meshes.

I will post examples of this problem soon.

**Comment by xylar** [comment]
This run is available on HPSS at NERSC:
```
/home/f/forsyth/E3SMv2/v2.LR.historical_0101
```
At the moment, one year of sample data showing the issue is available on disk here:
```
/global/cfs/cdirs/e3sm/zhang40/e2c_tests/v2.mpassi_input/
```
VTK files for this data are here:
```
/global/cfs/cdirs/e3sm/xylar/e2c_tests/v2.mpassi_input/vtk_files/
```

**Comment by xylar** [comment]
## Sea-ice thickness in problem areas

Western Ross Shelf, Antarctica:
![Western_Ross](https://user-images.githubusercontent.com/4179064/197842700-62c0ca66-a4a4-4b80-98dc-a9b915cbb775.png)

Disko Bay, Greenland:
![Disko_Bay](https://user-images.githubusercontent.com/4179064/197842690-e15aaafe-dc99-43e8-83e9-575f22e6f000.png)

A plot of a field on vertices (zonal velocity in this case) shows the vertex configuration:
![Western_Ross_vert](https://user-images.githubusercontent.com/4179064/197842970-1d003cee-389c-442a-a743-f16939dee859.png)
![Disko_Bay_vert](https://user-images.githubusercontent.com/4179064/197842965-f5667673-babb-476e-a7c6-22b0acef8f43.png)

In both cases, there is poor connectivity to the open ocean but (I believe) a configuration that passes our current algorithm for finding isolated sea-ice regions.

**Comment by xylar** [comment]
There are many other places with similar topology where sea ice does not build up so it must result from a combination of factors (e.g. both mesh topology and atmospheric forcing).

**Comment by xylar** [comment]
It seems safest to me to widen these "necks" to be 2 cells wide.  We widen the rest of a deeper bay (e.g. the one above left in the Canadian Archipelago) to be 2 cells wide and we should do the same at the "neck".  My proposal would be that the `cellsOnCell` of all cells must be adjacent to one another (at least in sea-ice regions).  If they are not, we would "dig" one of the intermediate cells so they become adjacent.  (Which one would be arbitrary).

**Comment by xylar** [comment]
@mark-petersen (and any one else interested), please let me know what you think.

**Comment by xylar** [comment]
@eclare108213, @akturner, @njeffery, this may be something you want to weight in on, too.

**Comment by xylar** [comment]
@vanroekel and @golaz, is this something you had already taken note of in this simulation?

**Comment by milenaveneziani** [comment]
Just a comment to say that we have experienced the same with the ARRM mesh.
I think it is a combination of 'bottle-neckness' and topography, so I guess geometry in general. With the old ARRM mesh, we got crazy values of ice thickness in some points (hundreds of m), but with the new mesh we are getting more reasonable values (still high, but more like tens of m).

One thing to say is that it is possible that land-ice will help in all these cases.

**Comment by xylar** [comment]
@milenaveneziani, thanks!  Sorry I forgot to ping you, too.

**Comment by xylar** [comment]
I would think land-fast ice would only exaggerate this problem but that's only a guess.

**Comment by milenaveneziani** [comment]
I guess I imagine all these cases would be handled as land-fast ice and not cause instability problems.

**Comment by xylar** [comment]
I see.

**Comment by eclare108213** [comment]
Keep in mind that the sea ice dynamics in MPAS-SI is on a B-grid, and so narrow inlets like this are stuck.  Ice growth like this is seen in other climate models as well. Sometimes it is due to "jiggling" by residual elastic waves in the solution, which acts like an ice growth pump -- the ice cracks, open water forms, new ice freezes then gets ridged into thicker ice.  CESM has also seen this associated with runoff from the land model making the ocean surface very fresh.  You could check what the fraction of ridged ice in the grid cells, if you have that diagnostic turned on.  Unless you care about what's happening in those small inlets, this kind of thing usually can be ignored for climate runs.  NOAA hates it in their forecast models, understandably...

**Comment by xylar** [comment]
@eclare108213, this is very helpful intuition.  I'll leave it up to others if you want to investigate the level of ridging going on in this simulation.  It certainly might be informative.  I would tend to agree that this buildup is probably harmless in these simulations as long as it doesn't cause numerical issues.

I would still advocate that we try to avoid these narrow inlets in future meshes.

**Comment by milenaveneziani** [comment]
> I would still advocate that we try to avoid these narrow inlets in future meshes.

We discussed this extensively, with @mark-petersen as well, in the summer, when we were making the new ARRM mesh. The current algorithm for opening up passages and small bays is working as it should be, with a minimum of 2 open edges (1 vertex) present when doing the culling. We could try making that criteria more stringent, maybe have a minimum of 4 edges or 2 vertices available, especially poleward of a certain latitude. And see if we still get these build-ups.

**Comment by xylar** [comment]
Again, I think having 2 open edges is not quite enough.  I think the problem comes up when those 2 open edge on each side with a closed edge between them.  I think you need to have at least 2 open edges, and all open edges need to be adjacent to one another.

**Comment by milenaveneziani** [comment]
>  I think you need to have at least 2 open edges, and all open edges need to be adjacent to one another.

I believe this is what the *current* algorithm does, so we'll need more than that. At least until MPAS-Seaice remains on a B-grid. We may need two open vertices, so 2edges+2edges.

**Comment by mark-petersen** [comment]
@xylar thanks for posting this. I agree that these are the cells that are causing problems, and that they are allowed by design in the current meshing algorithm:
![image](https://user-images.githubusercontent.com/4036816/200359304-9945458e-d683-4f61-bb7b-e9e4874c32ce.png)
See posting at https://github.com/MPAS-Dev/compass/pull/414#issuecomment-1186041258. 

We thought that, with sea ice on a B-grid, one active vertex (i.e. two neighboring active edges) would be enough to allow sea ice advection through these cells. Based on the [first image](https://github.com/MPAS-Dev/compass/issues/444#issuecomment-1290908262) in this post, that is obviously not true, as 73m-thick ice is not reasonable.

I can look at culling code to see what is required. This is a good time, as we could make a slight mesh revision before the V3 tuning and simulation campaign.

**Comment by mark-petersen** [comment]
The code that removes cells with isolated edges is here:
https://github.com/MPAS-Dev/MPAS-Tools/blob/master/conda_package/mpas_tools/ocean/coastline_alteration.py#L187-L188

For each cell, we check to see if it has any isolated edges, i.e. wet edges where both the next and previous edges on that cell neighbor a land cell. These are "single-edge-wide channels". The examples in this issue are double-edge-wide channels. One option is to add to this step a search for cells with two consecutive wet edges on a cell, with a land edge on both sides of those. It would add another loop like this:
https://github.com/MPAS-Dev/MPAS-Tools/blob/master/conda_package/mpas_tools/ocean/coastline_alteration.py#L209-L212
but testing for an `activeNextNextEdge` or similar.

A problem with this approach is that it is likely too conservative. Taking a snapshot of Baffin Bay from the top of this issue, all the circled cells have two-wide channels connected to the open ocean, but only that one causes the sea ice pileup problem. I don't think we want to remove all of these.

![image](https://user-images.githubusercontent.com/4036816/200392726-6c292d01-746d-42d4-9b9b-adfd937eb29e.png)

The problem seems to occur when there is an inlet with several cells connected to the open ocean with two-edge-wide channels. So we could test for cells that have TWO double-edge-wide channels, and cull those. On the original image, for example, these cells would be removed, as well as neighboring cells not connected to the global ocean:
![image](https://user-images.githubusercontent.com/4036816/200397352-f6dc95ae-dbbf-48b8-b6e1-3d5ae4e4a28f.png)
Here the red and pink circles all qualify as having two double-edge-wide channels. But I think we could test whether only one of those channels is connected to the global ocean flood-fill (red) or if both channels do (pink), and only remove the red ones. This sounds like the right level of culling to me, if we can figure out how to do it.

**Comment by mark-petersen** [comment]
The simplest thing to try first is to cull cells in [step 2](https://github.com/MPAS-Dev/MPAS-Tools/blob/master/conda_package/mpas_tools/ocean/coastline_alteration.py#L187-L188) with two double-wide channels (for a six-sided cell, edges have to be wet, wet, land, wet, wet, land). That avoids another flood-fill. It would include the pink circled cells above, but we could see how many cells that actually changes in practice.

**Comment by proteanplanet** [comment]
Thanks to @milenaveneziani who just made me aware of this issue.  

A common cause of sea ice thickness build-up in culverts in coupled models is that the land model physics overbear the sea ice response due to a coarse resolution atmospheric mesh.  No amount of culling of ocean model grid points can fix the problem, and it's simply something we have to live with for the model configuration unless we are clever as to how to tackle it. 

What can occur is land grid point are more heavily weighted than the ice-ocean grid point under a single atmospheric cell, and as a result the radiative feedback from the land grid point dominates.  One example of this is the removal of thick ice against the Archipelago in E3SM, where snow from the land model completely melts in spring, and therefore the atmosphere sees a much lower albedo than it would under just sea ice, which results in sea ice melting faster than replenishing advection, setting up a negative feedback.  The thick ice equivalent discussed here is where a land grid point is much colder or snowier than the equivalent for sea ice, and no matter that this causes sea ice to grow which would normally regular the response without sharing an atmospheric grid point with the land model, a positive feedback is created.  

There can be other dynamical and thermodynamic reasons for the positive feedback that I won't go into here.  But the main point is that cell culling is not a good solution to the problem of positive and negative coupled sea ice feedbacks without due consideration to the land and atmospheric meshes and also without being certain that the feedback cannot be mitigated within the sea ice code itself.   

For an increasing number of reasons, I am analyzing the contribution of coupled grid overlap and resolution to feedbacks and will post back here when I have some insights to share.

**Comment by xylar** [comment]
Okay great, thanks @proteanplanet.  This sounds like similar intuition (with some important new details) to what @eclare108213 posted.  I think we can be reasonably confident that compass is not the place to address this issue.  I'm happy to keep it open here for further discussion but it might make more sense to move the discussion elsewhere if there's an appropriate place.

**Comment by milenaveneziani** [comment]
My take is that, since this issue does not impact the climate (as the unrealistically thick ice remains anchored and does not affect the large scale ice distribution), then we as climate modelers do not worry about it for low and even higher resolution configuration. *But* I do feel that, when we will move to much higher res, for one reason or the other (Interface or Hilat problem, or any other polar coastal application), then maybe we should investigate more closely whether we can minimize the problem by adjusting the geometry. Especially in applications where the atmosphere is also high resolution.

**Comment by xylar** [comment]
I'm closing this because we likely won't be addressing in in compass based on the discussion so far.
