### ISSUE TITLE
Questions on when to run ./conda/configure_compass_env.py

### ISSUE THREAD

**Issue by mark-petersen** [MPAS-Dev/compass#458]
These questions involve the command 
```
./conda/configure_compass_env.py --conda ~/miconda3 --compiler gnu
```

1. When do we need to re-run this command? I assume I need to run it every time I update master. But when people add small update commits to PRs, do we rerun or can I just keep the old one?
2. My typical workflow is to have `compass/master` and `compass/pr` directories, and others I'm developing in.  If I use the identical command above in both directories, is there any conflict with them all using the same `~/miconda3` directory?
3. In my `compass/pr` directory, when I switch to a new PR branch to test, do I rerun the `configure_compass_env.py` every time as a first step?

**Comment by xylar** [comment]
1. You need to rerun anytime you are on a new branch or worktree, or update master.  What really matters is if the compass version and/or any of its dependencies have changed.  Sometimes you don't know so it's safest to run when you update master or switch branches.
2. Yes, you should use `--env_name` to get different environments for those different directories.  Otherwise, you are always competing with yourself.
3. Yes, I don't imagine there's a big advantage in using the same `compass/pr` directory for testing different branches.  I think you will want to use a different worktree for each and use an different `--env_name` to test each.  Then, just delete the worktree and compass env once you're done.

Let me know if that answers your questions.  Do you know how to delete a conda env when you don't need it?
```
conda remove --all -y -n <env_name>
```
Ideally, do this from the `base` environment, though the important thing is that you're not actually in the environment while you're trying to delete it.

**Comment by xylar** [comment]
@mark-petersen, is this resolved?

**Comment by mark-petersen** [comment]
Yes, thanks for the answer.
