### ISSUE TITLE
request to add separate compare pass/fail status

### ISSUE THREAD

**Issue by mark-petersen** [MPAS-Dev/compass#59]
It would be really helpful for suites with `-b` to report the test result and the comparison result separately:
```
ocean/baroclinic_channel/10km/default
  PASS  compare: PASS
ocean/baroclinic_channel/10km/threads_test
  PASS  compare: FAIL
ocean/baroclinic_channel/10km/decomp_test
  FAIL  compare: FAIL
````
Right now, FAIL could indicate the comparison or the run itself. The two are obviously both checked lower down, but I think only one is passed up to the suite function for reporting.

**Comment by xylar** [comment]
@mark-petersen, I looked into this and this could be a bit tricky.  I want to make sure I understand the expected behavior before I start implementing a solution.

Currently, test cases and their steps fail by raising python exceptions.  No distinction is made between failing because a step in the test case raised an exception and because validation raised an exception.

Presumably, when an exception is raised in a test case before validation, the expected behavior is not to perform validation at all.  The test case has failed so validation is likely not useful.  So in the example above:
```
ocean/baroclinic_channel/10km/decomp_test
  FAIL  compare: SKIP
```
or just
```
ocean/baroclinic_channel/10km/decomp_test
  FAIL
```
might make more sense, right?

Currently, the exception raised when comparison fails is a `ValueError`, which is too generic an exception to distinguish from other reasons for the test case to have failed.  My proposed solution would be to implement a `CompassValidationError` that would be specific to validation.

Another issue is that there is currently no way to tell the difference between a test case that includes validation, and that validation passed vs. a test case that does not perform validation.  Is it reasonable to say:
```
ocean/baroclinic_channel/10km/default
  PASS  compare: PASS
```
if the `default` test case didn't actually do any validation?  My feeling is it isn't.

**Comment by xylar** [comment]
Currently, the first call to `compare_variables()` that fails will raise an exception and subsequent validation will not be performed (though all variables in the call are checked before an exception is raised).  This may also not be the desired behavior, since it would be more helpful to have all validation take place before the test case fails.

Accommodating this and also making a distinction between test cases that have validation that passes and those that have no validation will likely require changes to the API of `compare_variables()`, which will affect about 40 locations in the current code.  This would be important to add before more test cases get added and the work is compounded.

**Comment by xylar** [comment]
Things are even more complicated than I realized in my discussion so far.  We currently don't distinguish between validation that fails during comparison within a test case and validation that fails in comparison with a baseline.  That's really going to be tricky!

**Comment by xylar** [comment]
Okay, I've got what seems like a working solution here: https://github.com/xylar/compass/tree/separate_compare_output.  Something for a follow-on PR once #28  goes in...

**Comment by xylar** [comment]
Here is the output from from a few nightly tests:
```
ocean/global_ocean/QU240/PHC/RK4/performance_test
  PASS  compare: PASS
ocean/global_ocean/QU240/PHC/RK4/restart_test
  FAIL  compare: PASS
  see: case_outputs/ocean_global_ocean_QU240_PHC_RK4_restart_test.log
```
The comparison between the full run and the restart in the RK4 restart test has been failing since the test was created.  Interestingly, the test fails but the comparison of both the full run and the restart with the baseline passes.  I thought something was wrong at first but this is, indeed, the case.

**Comment by mark-petersen** [comment]
Great! That is perfect! Yes, we could have a FAIL and PASS on compare, because it is comparing the first restart runs on the two regression suites.
